version: "3.9"
services: 
  db: 
    image: postgres:latest
    environment: 
      POSTGRES_DB: "telebook"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      PGPORT: 1234
    ports: 
      - "1234:1234"
  sort: 
    build: .
  nginx: 
    image: nginx:latest 
    ports:
      - "8000:80"
  