version: "3.9"
services: 
  db: 
    image: postgres:latest
    environment: 
      POSTGRES_DB: "telebook"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    ports: 
      - "5432:5432"
  sort: 
    build: .
    